### ISSUE TITLE
Test Modbus data on Conext RL

### ISSUE THREAD

**Issue by grendy** [uazure/conext-logger#3]
How to test/read modbus data from conext RL in PC using modbus-rtu?

**Comment by uazure** [comment]
Take a look into [app/conext-rl-module.js](https://github.com/uazure/conext-logger/blob/master/app/conext-rl-module.js). It's the class that provides basic interface to access ConextRL data via modbus.

Also I created file for convenient testing of modbus connectivity, here is it [app/testModbus.js](https://github.com/uazure/conext-logger/blob/master/app/testModbus.js).

Open app/testModbus.js and check your inverterId and modbus configuration, then run it with node.
Hope that helps.

**Comment by grendy** [comment]
Thanks a lot, that's work for me
